#codificació celles
OUT_OF_BOUNDS_CELL = -4
BOMB_CELL = -3
HIDDEN_CELL = -2
FLAGGED_CELL = -1
EMPTY_CELL = 0

#display ctts
CELLSIZE_PIXELS = 32
DEFAULT_W = 10
DEFAULT_H = 5

#nn ctts
NUM_CHANNELS = 12
HIDDEN_CHANNEL = 0
FLAGGED_CHANNEL = 1
REVEALED_BASE_CHANNEL = 2
OUT_OF_BOUNDS_CHANNEL = 11